### ISSUE TITLE
Custom theming

### ISSUE THREAD

**Issue by Zenahr** [codbear/reactable#6]
I read the pointers on the [readme](https://github.com/codbear/reactable#custom-table) about adding custom theming. But all it says is to use the `useTable`. I don't really know what I'm supposed to do based on that.

I did look at the source code linked in that section too, but didn't gather anything useful out of it for me.

Could you outline the steps to take so you could override the styling and, e.g., change the filling color to your liking or maybe even supply a theme.

If it was possible to somehow deactivate the styling in total this would solve this issue really well, as I already have custom styling in place for tables and I would imagine a lot of other users have a similar setup.

Again though, awesome stuff! This lib really hits the balance between having a simple API and offering enough extra stuff like the global search (which I ♥)

**Comment by codbear** [comment]
Hello @Zenahr thanks for your feedback!

I initially relied on Mui for theming, but indeed didn't offer much possibility to override it.

The custom section of the readme basically says that you can create your own components to render ui, hydrated by `useTable` as in the [Table component](https://github.com/codbear/reactable/blob/main/src/lib/components/Table/Table.jsx)

Since this is kind of an extreme solution for just having custom theming, I will implement your suggestion to provide a custom theme or disabling it 👍

**Comment by codbear** [comment]
closed by #7
